/**
 * Generates migrations/desktop.sql: desktop-only tables + sync outbox triggers.
 * Re-run (npm run schema) whenever the schema or lib/desktop-sync/registry.ts changes.
 * The file is idempotent and applied on every app start.
 */
import fs from 'fs';
import path from 'path';
import { Prisma } from '@prisma/client';
import { SYNC_ROOTS } from '../lib/desktop-sync/registry';

const table = (model: string) => {
  const m = Prisma.dmmf.datamodel.models.find((x) => x.name === model);
  if (!m) throw new Error(`Unknown model ${model}`);
  return m.dbName || m.name;
};

const NOW_MS = "CAST((julianday('now') - 2440587.5) * 86400000 AS INTEGER)";
const GUARD = `vt_tracking() = 1 AND (SELECT value FROM "_desktop_state" WHERE key = 'sync.tracking') = '1'`;

const out: string[] = [
  '-- AUTO-GENERATED by scripts/gen-desktop-sql.ts. Applied on every start (idempotent).',
  'CREATE TABLE IF NOT EXISTS "_desktop_state" ("key" TEXT NOT NULL PRIMARY KEY, "value" TEXT);',
  'CREATE TABLE IF NOT EXISTS "_sync_outbox" ("seq" INTEGER PRIMARY KEY AUTOINCREMENT, "model" TEXT NOT NULL, "root_id" TEXT NOT NULL, "at" INTEGER NOT NULL);',
  'CREATE INDEX IF NOT EXISTS "_sync_outbox_model_root" ON "_sync_outbox" ("model", "root_id");',
  '',
];

function triggers(tbl: string, rootModel: string, idCol: string) {
  const name = (op: string) => `"vt_sync_${tbl}_${op}"`;
  const ins = (ref: 'NEW' | 'OLD') =>
    `INSERT INTO "_sync_outbox" ("model", "root_id", "at") SELECT '${rootModel}', ${ref}."${idCol}", ${NOW_MS} WHERE ${ref}."${idCol}" IS NOT NULL;`;
  for (const [op, ev, ref] of [
    ['ai', 'AFTER INSERT', 'NEW'],
    ['au', 'AFTER UPDATE', 'NEW'],
    ['ad', 'AFTER DELETE', 'OLD'],
  ] as const) {
    out.push(`DROP TRIGGER IF EXISTS ${name(op)};`);
    out.push(`CREATE TRIGGER ${name(op)} ${ev} ON "${tbl}" WHEN ${GUARD} BEGIN ${ins(ref)} END;`);
  }
  // A child moved to another parent must also refresh the old parent.
  if (idCol !== 'id') {
    out.push(`DROP TRIGGER IF EXISTS ${name('au_old')};`);
    out.push(
      `CREATE TRIGGER ${name('au_old')} AFTER UPDATE OF "${idCol}" ON "${tbl}" WHEN ${GUARD} AND OLD."${idCol}" IS NOT NEW."${idCol}" BEGIN ${ins('OLD')} END;`
    );
  }
}

for (const root of SYNC_ROOTS) {
  triggers(table(root.model), root.model, 'id');
  for (const child of root.children || []) triggers(table(child.model), root.model, child.fk);
}

const file = path.join(__dirname, '..', 'migrations', 'desktop.sql');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, out.join('\n') + '\n');
console.log(`Wrote migrations/desktop.sql (${SYNC_ROOTS.length} roots)`);
